### ISSUE TITLE
Request: Snes Version

### ISSUE THREAD

**Issue by DQ318** [nfam/nes-web#1]
Congratulations for the excellent work!
Your application is wonderful. Really enjoyed.
Would it also be possible to use the Super Nintendo platform in your application, for example using an emulator like "snes9x" or even a javascript emulator?
I would love to see a version with Super Nintendo or, if you can help me make one, I'll be happy to build it!
Again, congratulations on the gritty work.
Cheers!

**Comment by DQ318** [comment]
Hi, @nfam.

How do I get access to all application files after pulling your docker image?
I tried to create my own image using only the font contained here in your github repository however the application does not start any page.
When I use yours, everything works perfectly but I can not edit anything, including the language because I can not access the files that are running in the container.
Would you help me?
Thank you.

**Comment by nfam** [comment]
@DQ318 Thank you for your willing to help. Unfortunately, I've been busy lately, and don't have plan for SNES.

For docker image, you can fork then modify source code, then use Dockerfile to build image. I suggest to test on your local machine beforehand, run following commands (similar to those in Dockerfile):

build
```sh
npm install
npm run build
```

make data directory, and put your own `.nes` roms in `dist/data/roms`
```sh
mkdir -p dist/data/roms
mkdir -p dist/data/screen
```

start server
```sh
node dist/server/index.js
```

**Comment by DQ318** [comment]
Thanks for answering.
I downloaded your repository so I did the procedure and, when doing the command
"npm run build" I came across the following error:

> > nes-web@0.1.0 build /home/ellus/Downloads/nes
> > gulp
> 
> sh: 1: gulp: not found
> 
> npm ERR! Linux 4.15.0-43-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! nes-web@0.1.0 build: `gulp`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the nes-web@0.1.0 build script 'gulp'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the nes-web package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     gulp
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs nes-web
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls nes-web
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ellus/Downloads/nes/npm-debug.log

 Could you give me a chance to get around this problem?
Thank you very much.
Cheers!

**Comment by DQ318** [comment]
Hi, @nfam!

Thanks for answering.
I downloaded your repository so I did the procedure and, when doing the command
"npm run build" I came across the following error (I have gulp installed as well):

> > nes-web@0.1.0 build /home/ellus/Downloads/nes
> > gulp
> 
> 
> sh: 1: gulp: not found
> npm ERR! Linux 4.15.0-43-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! nes-web@0.1.0 build: `gulp`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the nes-web@0.1.0 build script 'gulp'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the nes-web package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     gulp
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs nes-web
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls nes-web
> npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ellus/Downloads/nes/npm-debug.log

Could you give me a chance to get around this problem?
Thank you very much.
Cheers!

**Comment by nfam** [comment]
Hi, @DQ318 
I cloned the repo and run on clean machine with node installed only (**no gulp installed beforehand** so gulp will be installed in local `node_module`), and it worked.

If you have `gulp-cli` installed globally, can you try `gulp` instead of `npm run build`?

**Comment by DQ318** [comment]
Thank you, really, for helping me.
I was making a little mistake and installing NPM globally, not locally in the application folder, so it was not working.
However, now the application seems to have compiled correctly but I think some files are missing because on accessing LOCALHOST, the home page loads forever and does not list the games or options, as in the Docker image (I have already created the directories and put a .NES file and a .PNG with the same names.).
What could it be?

Thanks for listening.

![2](https://user-images.githubusercontent.com/43095999/52360815-086c1100-2a24-11e9-8619-27c58a78e1a2.jpg)

![1](https://user-images.githubusercontent.com/43095999/52360822-0bff9800-2a24-11e9-8a03-67253f40c127.jpg)

**Comment by nfam** [comment]
The loading indicator is still showing on your browser, it seems like due to JS error. Open your browser debugger and see what the web console would say.

**Comment by DQ318** [comment]
Hi, @nfam!

Right. What appears here to me are the errors listed below. It may be missing a file because I just cloned the repo and mounted the build just as you had taught.

My errors are these:

> Loading failed for the <script> with source “http://localhost:8080/cdn/zone.js@0.8.18/dist/zone.min.js”. localhost:8080:27
> Loading failed for the <script> with source “http://localhost:8080/cdn/reflect-metadata@0.1.10/Reflect.js”. localhost:8080:28
> Loading failed for the <script> with source “http://localhost:8080/cdn/systemjs@0.19.47/dist/system.js”. localhost:8080:29
> Loading failed for the <script> with source “http://localhost:8080/cdn/rxjs-system-bundle@5.5.2/Rx.system.min.js”. localhost:8080:30
> Loading failed for the <script> with source “http://localhost:8080/cdn/simple-peer@8.1.1/simplepeer.min.js”. localhost:8080:31
> [Show/hide message details.] ReferenceError: System is not defined[Learn More] app.js:1:580
> <anonymous>
> http://localhost:8080/assets/app.js:1:580
> [Show/hide message details.] ReferenceError: System is not defined[Learn More] localhost:8080:35:5
> <anonymous>
> http://localhost:8080/:35:5
> <anonymous>
> http://localhost:8080/:34:2
> [Show/hide message details.] ReferenceError: System is not defined[Learn More] localhost:8080:56:5
> <anonymous>
> http://localhost:8080/:56:5

**Comment by nfam** [comment]
Hi @DQ318 
I updated the package `gulp-download-stream` in `package.json` to the latest. Please download and run `npm install` again.

**Comment by DQ318** [comment]
Hi, @nfam.

Thank you very much for taking the time to help with the installation of the project.
I just tested and it was really FANTASTIC!
Now I'm going to do some tests and see how the code works and I'm trying to help you to increase new features going forward.
If you can give me some tips on how to implement a snes emulator in your project, I believe that using emscripten you can convert snes9x and apply, right?
Again, thank you for donating your time to help.
Cheers!

**Comment by DQ318** [comment]
Hello @nfam, Are everything okay with you, my friend?

I've been trying to make adaptations to convert your application to SNES, but I did not get anything.
Could you give me some guidelines on how to proceed?
Apparently just an emulator in javascript, right?
If it's interesting to you, we can combine it as a freelancer proposal if you can, of course.

Cheers!

**Comment by nfam** [comment]
If you want to replace my NES engine with your SNES engine, you need to make your API compatible to mine.
This is the definition of NES emulator API [https://github.com/nfam/tsnes/blob/master/dist/nes.d.ts](url)

`onsample` is the audio callback. Ignore this if you use `pull()`
`onerror` is the error callback.
`load()` is to load your SNES game.
`frame()` call this function 24 times per second (like movie). This is like the heart beat of emulator, if you don't call this function, consider it as pausing the emulator.
`pull()` to get the current screen bitmap and audio sequence.

I recommend you to ignore audio first and make it playable with video only.

**Comment by DQ318** [comment]
Thank you for the tips, @nfam .
But how do I make this replacement? Do I need to convert snes9x to javascript?

**Comment by nfam** [comment]
1. The app is **nes-web**, thus, your snes emulator must be written in JavaScript or TypeScript.
2. My emulator is **tsnes**, search in source code.
